name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    name: Mark PRs as Stale
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Mark PR
        uses: p6m7g8-actions/p6-gh-pr-stater@main
